### ISSUE TITLE
Adicionar tag noscript na barra (correção de acessibilidade)

### ISSUE THREAD

**Issue by rodfersou** [plonegovbr/brasil.gov.barra#11]
A [tag script](https://github.com/plonegovbr/brasil.gov.barra/blob/3cf928cd5ea270086d6097a1e263f7ef7aea6247/src/brasil/gov/barra/browser/templates/barra.pt#L26-L27) do brasil.gov.barra não possui conteúdo alternativo para leitores de tela que não possuem suporte a javascript.

Devemos adicionar uma tag noscript conforme [esse exemplo](https://github.com/collective/sc.social.like/blob/master/sc/social/like/plugins/twitter/templates/plugin.pt#L11-L13).

Seu conteúdo pode ser simplesmente um link apontando para algum site que explica o que é a barra, ou alguns links com os mesmos conteúdos da barra.

Exemplo link:

    <noscript>
        <a href="http://epwg.governoeletronico.gov.br/barra/">Barra de identidade do governo</a>
    </noscript>

Exemplo replicando conteúdo (acredito que seria mais interessante assim):

    <noscript>
        <div id="wrapper-barra-brasil">
            <div class="brasil-flag">
                <a href="http://brasil.gov.br" class="link-barra">Brasil</a>
            </div>
            <span class="acesso-info">
                <a href="http://brasil.gov.br/barra#acesso-informacao" class="link-barra">Acesso à informação</a>
            </span>
            <ul class="list">
                <li class="list-item first"><a href="http://brasil.gov.br/barra#participe" class="link-barra">Participe</a></li>
                <li class="list-item"><a href="http://www.servicos.gov.br/" class="link-barra">Serviços</a></li>
                <li class="list-item"><a href="http://www.planalto.gov.br/legislacao" class="link-barra">Legislação</a></li>
                <li class="list-item last last-item"><a href="http://brasil.gov.br/barra#orgaos-atuacao-canais" class="link-barra">Canais</a></li>
            </ul>
        </div>
    </noscript>

**Comment by valessiobrito** [comment]
@rodfersou  essa instrução foi feita.  Pode conferir aqui:  https://barra.brasil.gov.br/

Pode fechar a Issue.

**Comment by idgserpro** [comment]
Acho que essa issue pode ser fechada e a discussão sobre esse formato discutido na #12 pois mais modificações na barra serão necessárias e lá há mais informações.
