### ISSUE TITLE
Atender novas regras da barra: chamar no fim da tag body e uso do html da barra quando o javascript não puder ser carregado.

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.barra#12]
~~Não há versionamento da barra (por isso o pedido genérico "Atender novas regras da barra"), mas de acordo com as diretivas presentes na [Identidade Visual do Governo Federal na Internet] (http://epwg.governoeletronico.gov.br/barra/), visitado em 03/2015, a chamada deveria ser precisamos de:~~

~~<script defer="defer" async="async" src="//barra.brasil.gov.br/barra.js" type="text/javascript"></script>~~

~~E não explicitando `http://` como é hoje na [template](https://github.com/plonegovbr/brasil.gov.barra/blob/master/src/brasil/gov/barra/browser/templates/barra.pt). Assim, usando `//` o protocolo utilizado seria herdado do portal em questão. *hard-coded* como está hoje, ocorrem problemas no navegador Chrome por exemplo que não permite baixar um recurso http se o site for https por questões de segurança.~~

~~Além disso outras duas modificações devem ser feitas:~~

- A chamada é recomendada no fim da tag body. Sugestão: estudar a vantagem/viabilidade de uso de viewlets registradas no footer para essa chamada do script;
- Alterar brasil.gov.temas. Em `index.html` adicionar `<div id="barra_brasil_js"></div>` e em `rules.xml` adicionar `<replace css:theme="#barra_brasil_js" css:content-children="#barra_brasil_js" />`;
- Uso do html da barra quando o javascript não puder ser carregado (favor copiar diretamente [do site da barra](http://barra.governoeletronico.gov.br/), o código abaixo é mais por referência). Lembrando que esse código é recomendado no *início* da tag body.

```
<div id="barra-brasil" style="background:#7F7F7F; height: 20px; padding:0 0 0 10px;display:block;"> 
	<ul id="menu-barra-temp" style="list-style:none;">
		<li style="display:inline; float:left;padding-right:10px; margin-right:10px; border-right:1px solid #EDEDED"><a href="http://brasil.gov.br" style="font-family:sans,sans-serif; text-decoration:none; color:white;">Portal do Governo Brasileiro</a></li> 
		<li><a style="font-family:sans,sans-serif; text-decoration:none; color:white;" href="http://epwg.governoeletronico.gov.br/barra/atualize.html">Atualize sua Barra de Governo</a></li>
	</ul>
</div>
```

~~Além disso, uma modificação em brasil.gov.temas será necessária para que browsers que ainda não tenham aceitado o certificado da barra mostrem a imagem nova do footer e não a antiga. Ver https://github.com/plonegovbr/brasil.gov.temas/issues/109. Seria interessante que ambas as correções saíssem num mesmo release.~~

Após essas mudanças, poderemos atender ao relato da barra local ser uma cópia fiel da barra original em https://github.com/plonegovbr/brasil.gov.barra/issues/30.

**Comment by hvelarde** [comment]
podemos fechar já?

**Comment by idgserpro** [comment]
Não. Complementei com mais informações do que deveria ser feito nesse pacote e em brasil.gov.temas para que tanto a barra quanto o rodapé funcionem da melhor forma possível.

**Comment by winstonf88** [comment]
@idgserpro Este item já foi fechado, correto?

**Comment by idgserpro** [comment]
O único feito foi a não explicitação do protocolo.

Os itens:

* A chamada é recomendada no fim da tag body. Sugestão: estudar a vantagem/viabilidade de uso de viewlets registradas no footer para essa chamada do script;
* Uso do html da barra quando o javascript não puder ser carregado.

... ainda não foram feitos. Além disso, no caso da escolha de uma viewlet, é importante analisar se, na hora da renderização, ficará na posição como indicado pelo Ministério do Planejamento. Caso não fique, será necessária a criação de uma nova regra de Diazo em brasil.gov.temas. Por isso foi mencionado a questão do estudo da viabilidade.

**Comment by hvelarde** [comment]
acho melhor partir a tarefa em 3 e deixar as outras 2 separadas para retomar depois.

**Comment by winstonf88** [comment]
+1

**Comment by idgserpro** [comment]
Feito em https://github.com/plonegovbr/brasil.gov.barra/pull/36 e https://github.com/plonegovbr/brasil.gov.temas/pull/134
