### ISSUE TITLE
Fazer cache da barra.js (definir expiração)

### ISSUE THREAD

**Issue by valessiobrito** [plonegovbr/brasil.gov.barra#16]
Precisamos definir um valor para expirar a cache do barra.js  o mesmo parece não esta fazendo cache no navegador e recarregado a cada reload de página.

Identifiquei que não esta fazendo cache através da ferramenta PageSpeed[1], ele retorna um aviso:  expiração não especificada para o barra.js

Recomendações para solução[2] através da cofiguração no servidor web.

[1] https://developers.google.com/speed/pagespeed/insights/
[2] https://developers.google.com/speed/docs/insights/LeverageBrowserCaching

**Comment by valessiobrito** [comment]
Imagem anexa com parte do resultado PageSpeed.

**Comment by valessiobrito** [comment]
Imagem com resultado específico do PageSpeed:

![pagespeed_insights_-_barrabrasil](https://cloud.githubusercontent.com/assets/310049/5671678/a1d5f2aa-9768-11e4-8e3a-876332e6a37f.png)

**Comment by garotadpi** [comment]
Valéssio;
Vou repassar para o pessoal de desenvolvimento.

**Comment by caduvieira** [comment]
@valessiobrito Foi feito um pedido em novembro/2014 para o SERPRO que só foi atendido em 12/01/2015 sobre compressão e cache da barra. Isso já foi feito e sugiro fechar essa issue. 

E sugiro para a comunidade que issues similares no futuro sejam abertas no github.com/govbr/brasil.gov.barra

**Comment by valessiobrito** [comment]
Sim, o pagespeed confirmou que o cache agora esta ativado.  :+1:    Fechando.
