### ISSUE TITLE
Barra não exibe itens menu abaixo de 670px 

### ISSUE THREAD

**Issue by valessiobrito** [plonegovbr/brasil.gov.barra#17]
Atualmente a Barra GovBr é responsiva, porém, quando em telas menores a 670px (alguns Tablets e aparelho celular);  O itens de menu de serviço desaparecem.  Isso não é uma boa prática.

Sugiro fazer um collapse  com as opções, ou seja, quando clicar em um icone  vai apresentar as opções.  Isso é possível fazer somente com CSS, veja este tutorial: http://blog.teamtreehouse.com/create-an-absolute-basic-mobile-css-responsive-navigation-menu

![barra-menu](https://cloud.githubusercontent.com/assets/310049/5837952/c7d03928-a16a-11e4-8da2-87fdb760e368.png)

**Comment by valessiobrito** [comment]
@caduvieira estou abrindo Issues aqui, mas favor, leve a equipe de devels.  Grato.

**Comment by caduvieira** [comment]
@valessiobrito 

Esse tipo de issue não é do plonegovbr e sim do govbr. De qualquer forma está pronto um RC.

Pode ver aqui:
http://barra.governoeletronico.gov.br/teste/

Não posso te prometer quando vai estar em produção pois é complicado saber o dia certo.

**Comment by garotadpi** [comment]
Olá!
Ainda temos que consultar a SECOM.

**Comment by valessiobrito** [comment]
@garotadpi sim, de acordo.    ;)
@caduvieira essa implementação "teste" precisa de ajuste;  O icone de 3 barras é muito além do qual foi ilustrado em minha montagem, isso causa uma distroção visual entre os elementos;    Outra coisa é a posição qual aparece as opções, ela esta sobrepondo a opção "Acesso à informação", ou seja, as opções devem/precisam aparecer alinhado abaixo da barra.

Feito isso, pode enviar a SECOM para aprovarem.  :+1:

**Comment by felipeduardo** [comment]
Lembrar o comportamento deve ser implementado com click e não com mouse over

Em 27 de janeiro de 2015 11:27, Valessio Soares de Brito <
notifications@github.com> escreveu:

> @garotadpi <https://github.com/garotadpi> sim, de acordo. ;)
> @caduvieira <https://github.com/caduvieira> essa implementação "teste"
> precisa de ajuste; O icone de 3 barras é muito além do qual foi ilustrado
> em minha montagem, isso causa uma distroção visual entre os elementos;
> Outra coisa é a posição qual aparece as opções, ela esta sobrepondo a opção
> "Acesso à informação", ou seja, as opções devem/precisam aparecer alinhado
> abaixo da barra.
>
> Feito isso, pode enviar a SECOM para aprovarem. [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plonegovbr/brasil.gov.barra/issues/17#issuecomment-71647057>
> .
>



-- 
Felipe Duardo

**Comment by caduvieira** [comment]
@valessiobrito Não entendi a frase 'O ícone de 3 barras é muito além...'. Você achou o ícone grande?

**Comment by valessiobrito** [comment]
@caduvieira sim, ele estoura o limite da barra; esta grande comparado com a proposta que desenhei.

**Comment by caduvieira** [comment]
@felipeduardo O click só por JS. O :active no css funciona enquanto estiver segurando. E o hover está funcionando como o clica e solta no dispositivo que estou testando. E não posso usar o '~' do css pois a imagem e a lista não estão no mesmo nível na árvore DOM.

@valessiobrito diminui e não está sobrepondo o "Acesso à Informação". Pode olhar novamente no teste

**Comment by valessiobrito** [comment]
@caduvieira aqui no firefox apareceu desalinhado, mas ainda podemos forçar a redução via CSS, sugiro testar:

````
#barra-brasil #menu-icon {
    display: inline-block;
    float: right;
    margin: 5px;
    background-size: 70%;
}
#barra-brasil .list {
    top: 32px;
    background: #EEE;
    width: auto;
}
#barra-brasil .list a:hover li {
    background: #DDD;
}
````

@felipeduardo o :mouseover em dispositivos touchscreen tem o comportamento do clique, porque o "dedo" aperta sobre a área :hover e apresenta os elementos;   Esta de acordo a implementação que foi feita, é similar do tutorial que indiquei quando abrir a Issue.

**Comment by felipeduardo** [comment]
Ok, fiz um teste aqui e funcionou!

e já que estão com a mão na massa poderiam ou usar um arquivo .svg na
bandeira do brasil ou usar uma imagem com melhor resolução, pois nos
aparelhos de tela de retina a imagem fica bem ruim...

Quanto a implementação do ícone com 3 "barrinhas" por que não usar o mesmo
modelo do bootstrap que ira se adaptar a qualquer resolução de tela

Em 27 de janeiro de 2015 15:23, Valessio Soares de Brito <
notifications@github.com> escreveu:

> @caduvieira <https://github.com/caduvieira> aqui no firefox apareceu
> desalinhado, mas ainda podemos forçar a redução via CSS, sugiro testar:
>
> #barra-brasil #menu-icon {
>     display: inline-block;
>     float: right;
>     margin: 5px;
>     background-size: 70%;
> }
> #barra-brasil .list {
>     top: 32px;
>     background: #EEE;
>     width: auto;
> }
> #barra-brasil .list a:hover li {
>     background: #DDD;
> }
>
> @felipeduardo <https://github.com/felipeduardo> o :mouseover em
> dispositivos touchscreen tem o comportamento do clique, porque o "dedo"
> aperta sobre a área :hover e apresenta os elementos; Esta de acordo a
> implementação que foi feita, é similar do tutorial que indiquei quando
> abrir a Issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plonegovbr/brasil.gov.barra/issues/17#issuecomment-71688525>
> .
>



-- 
Felipe Duardo

**Comment by caduvieira** [comment]
@felipeduardo Já tinha conversado aqui no Ministério sobre SVG e o problema é dar suporte ao IE8. Quando cair esse suporte pela barra irei alterar todos os ícones para SVG. E colocar uma imagem de melhor resolução é um problema devido ao tamanho que a barra.js ficaria. Foi tamanho a qualidade da imagem. E adicionar outra chamada a outra fonte fica inviável nesse momento.

@valessiobrito Ficou bem melhor visualmente sua sugestão de CSS. Dá uma olhada agora.

**Comment by valessiobrito** [comment]
@caduvieira esse "padding-top: 8px;"  distorce a visão no Firefox;   Porque esta usando ele?  Para o IE?   Sugiro colocar o hack-css para IE assim:

````
padding-top: 0px;
_padding-top: 8px;
````

**Comment by caduvieira** [comment]
Isso é para ficar o bloco da lista 'colado' com o ícone do menu. Retirei mas tive que modificar o top do .list. Se não fica junto fica impossível de acessar o menu com o mouse somente. 

Nova versão no teste.

**Comment by valessiobrito** [comment]
@caduvieira onde esta esse código para modificar e fazer um MR?   Acredito que preciso refatorar algumas coisas, já tem CSS sobreescrevendo outro;   Mas em geral, para ter uma área de ação maior sugiro colocar padding-top no UL;   E no icone, remove o border-radius e trocar o margin: 5px para um padding: 5px;  O  resultado fica bem agradável;

Outra tática para a lista aparecer de forma animada é não usar o display: none;   faz um  height: 0px com overflow: hidden;   e coloca um transition: 0.3s;  nessa UL;  e quando ativar o :hover aplica o height: auto.. ou seja, o menu vai aparecer gradativamente em 3 milesegundos;  Ai coloca um transition: 0.5s no conjunto especificado do :hover para que o out dure um pouco mais de tempo.


Enfim, se estiver se "divertindo" e fazer algo bem agradável, sugiro colocar animação; rs..  :+1:

**Comment by valessiobrito** [comment]
No mais, esta ficando muito bom!  Parabéns!

**Comment by caduvieira** [comment]
Está aqui:

https://github.com/govbr/brasil.gov.barra/blob/master/recipes/default/assets/estilo-barra.scss

2015-01-27 16:50 GMT-02:00 Valessio Soares de Brito <
notifications@github.com>:

**Comment by valessiobrito** [comment]
@caduvieira o mais chato foi fazer o ambiente de desenvolvimento rodar; Estava faltando algumas dependencias que não havia documentado no README.  Coloquei por lá também.   Fiz um pull request[1]. Faça testes e sua avaliação.    

Depois aguardamos a avaliação da SECOM.

;)

[1] https://github.com/govbr/brasil.gov.barra/pull/3

**Comment by valessiobrito** [comment]
Fechando essa Issue, agora deve ser tratada no repostirório oficial:  https://github.com/govbr/brasil.gov.barra/issues/4
