### ISSUE TITLE
Para evitar confusão de Issue:  plonegovbr fazer fork do repositório oficial

### ISSUE THREAD

**Issue by valessiobrito** [plonegovbr/brasil.gov.barra#18]
Ao que me parece o repositório oficial é este: https://github.com/govbr/brasil.gov.barra

Para questões de organização para futuras contribuições vinda da comunidade plonegovbr, a proposta é configurar esse fork para ter o origin no repo oficial: https://github.com/govbr/brasil.gov.barra

Ou uma simples descrição no assunto para quem chegar por aqui, ir ao repo oficial.

Prometo não abrir mais Issues por aqui, agora só lá.

**Comment by caduvieira** [comment]
Mudei o nome do projeto no govbr para barra.govbr para tentar diminuir a confusão. Os dois projetos são diferentes mesmo. Um para aplicar a barra no plone e outro de desenvolvimento da barra em si. Não são forks um do outro.

Sugiro fechar essa issue.
