### ISSUE TITLE
Ícone de Burger Icon é png e fica pixelado em displays retina 

### ISSUE THREAD

**Issue by sahrosa** [plonegovbr/brasil.gov.barra#22]
Olá! 

Percebi que o burger icon da Barra Brasil é um png que fica pixelado. Uma sugestão seria usar o ícone do Font Awesome! http://fortawesome.github.io/Font-Awesome/icon/bars/

O que acha @caduvieira?

**Comment by idgserpro** [comment]
Esse relato deve ser aberto no repositório [barra.govbr](https://github.com/govbr/barra.govbr), que é o repositório que implementa a barra. O brasil.gob.barra somente disponibiliza a barra em sites Plone.

**Comment by sahrosa** [comment]
Obrigada @idgserpro!
