### ISSUE TITLE
Qual o ponto em servir a barra localmente?

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.barra#23]
Na instalação do pacote se coloca, no ``portal_properties``, [uma propriedade](https://github.com/plonegovbr/brasil.gov.barra/blob/master/src/brasil/gov/barra/profiles/default/propertiestool.xml#L4) com valor ``False``.

Isso é usado depois numa [helper view](https://github.com/plonegovbr/brasil.gov.barra/blob/master/src/brasil/gov/barra/browser/helper.py#L34:L45) para definir [como será servido o arquivo main.css](https://github.com/plonegovbr/brasil.gov.barra/blob/master/src/brasil/gov/barra/profiles/default/cssregistry.xml#L8).

Qual a ideia disso e em quais situações a barra deveria ser servida localmente?

A documentação deveria ser atualizada.

**Comment by idgserpro** [comment]
@rodfersou e @ericof, tem alguma idéia da *motivação* dessa implementação já que são vocês nos últimos commits? Obrigado!

**Comment by ericof** [comment]
Isto remonta ao período em que não tínhamos a barra hosted. (E a única utilidade hoje em dia é ter uma barra quando se está sem Internet -- para ambientes de desenvolvimento)

**Comment by hvelarde** [comment]
ou seja, seria melhor remover.

**Comment by ericof** [comment]
Up to you. Eu acho mais fácil colocar a barra como local do que esperar alguns segundos até o timeout (quando em ambientes sem Internet)

**Comment by hvelarde** [comment]
essa funcionalidade pode ser utilizada para desabilitar coisas como a campanha do mosquito aedes aegypti em sites numa língua diferente do português:

http://www.brasil2016.gov.br/en/
http://www.brasil2016.gov.br/es/
