### ISSUE TITLE
Code analysis reporta vários problemas que devem ser consertados

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.barra#28]
https://travis-ci.org/plonegovbr/brasil.gov.barra/jobs/110413139#L3164

**Comment by idgserpro** [comment]
O último build do master, o https://travis-ci.org/plonegovbr/brasil.gov.barra/builds/167476172, nesse momento, passa o code-analysis. Portanto, esse relato pode ser fechado.
