### ISSUE TITLE
Barra local deveria ser simplesmente o barra.js presente em https://barra.brasil.gov.br/barra.js na pasta static do pacote

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.barra#30]
Hoje fazemos uma ["reimplementação" da barra](https://github.com/plonegovbr/brasil.gov.barra/blob/d97c33c85983e5bae317c61c73ee66e6abd27774/src/brasil/gov/barra/browser/templates/barra.pt), pegando *partes* do html que é gerado dinamicamente pelo https://barra.brasil.gov.br/barra.js e colocando nessa template.

Bem lá no início da implementação da barra, isso até fazia sentido, pois a barra era apenas uma div sendo colocada no topo: hoje, adiciona uma imagem svg em formato base64 de libras na barra, adiciona um rodapé (com uma imagem de governo em formato svg) e ainda manipula fontes. Ter uma barra local que é uma "reimplementação" de um js que já está pronto é retrabalho desnecessário.

Assim, propomos:

- A barra local deve ser simplesmente uma chamada ao barra.js só que pra um arquivo local, ou seja, um ++resource++. Após atender o relato https://github.com/plonegovbr/brasil.gov.barra/issues/12, devemos remover toda reimplementação customizada da barra e adicionarmos o barra.js numa pasta static do pacote;
- Um teste deve ser adicionado, com um timeout razoável, que baixa a última versão da barra e compara com a versão em disco, de forma que a barra local seja sempre a mais próxima possível da oficial.

Atendendo a esse issue, podemos fechar o https://github.com/plonegovbr/brasil.gov.barra/issues/24, não sendo necessário mais lógica de *fallback* da imagem de governo, e precisamos criar um novo issue pra remover essa imagem do tema.

**Comment by hvelarde** [comment]
a reimplementação da barra permitiu desativar os elementos invasivos inseridos nos sites a traves dela.

um exemplo é o site do [Portal Brasil 2016](http://www.brasil2016.gov.br/) onde os mosquitos da campanha contra a dengue e a Zika eram uma péssima ideai nos sites em inglês e espanhol.

**Comment by idgserpro** [comment]
Permitiu desativar mas não achamos que esse é o papel da barra local atual. Esse recurso de "desativar elementos invasivos" foi um efeito colateral da implementação atual da barra mas deveria ser resolvido no policy do portal, com o uso de jbot. Do jeito como está continua com o problema de ser uma reimplementação da barra oficial.

Exemplo: agora temos o recurso de libras na barra. Como fazer pra incorporar na barra local? Entrar no repositório da barra, vasculhar as modificações em svg, css, e reimplementar no brasil.gov.barra? Entrar em https://barra.brasil.gov.br/barra.js, copiar e colar apenas as partes importantes? Esse trabalho manual não só é improdutivo como aumenta a chance de erros e bugs.

Se a barra, que é a oficial, está aplicando os elementos invasivos, a reclamação deve ser com os responsáveis pela barra. Eles devem ser avisados do problema que é uma campanha invasiva em sites multilíngues do governo e chegar num consenso. Não devemos ficar implementando, em pacotes oficiais do IDG, formas de "burlar" algo que foi definido oficialmente pelo Ministério do Planejamento, ainda mais quando significa uma reimplementação.

A motivação desse relato é justamente a necessidade de, novamente, precisarmos trocar o *fallback* da imagem do rodapé, colocando a mais atual: se a barra local fosse o espelho do mais atual, além de resolver esse problema eliminaria o retrabalho de ficar refazendo essa barra. Seguir pelo caminho proposto nesse relato, a atualização é basicamente um `wget` da barra e colocar no pacote na pasta static, sem todo esse trabalho manual.

@caduvieira @rodfersou @ericof p/c

**Comment by rodfersou** [comment]
Acredito que seja bom mudar a configuração do pacote para estar preparado para compilar o arquivo ``.sass`` da barra ao invés de utilizar o ``.css`` gerado, assim teremos somente uma cópia do conteúdo original da barra.

**Comment by idgserpro** [comment]
Se formos por esse caminho @rodfersou, continuamos com a crítica da reimplementação: teria de estudar a lógica do `.sass` do https://github.com/govbr/barra.govbr, teríamos de colocar uma lógica de compilação de `.sass` no nosso pacote, acompanhar cada modificação dos arquivos `.sass`  no repositório da barra, ver no .js o que teríamos de usar ou não pra replicar em nossas templates...

... ou podemos simplesmente colocar o .js já compilado, pronto e testado, do jeito que tem de rodar, em nossa pasta static, e, na template onde testa `if local`, ao invés de renderizar nossa implementação atual chama o .js como um ++resource++. 

Criamos um teste que compara o .js do pacote com o original, assim cada build feita em brasil.gov.barra vai avisar se tem a última versão ou não da barra em javascript.

Envolve menos trabalho, menos reimplementação, menor chance de bugs e maior garantia de proximidade com a barra original. Acreditamos que em virtude da complexidade que se tornou a barra esse é o melhor caminho.

**Comment by hvelarde** [comment]
eu acabo concordando cm vocês, @idgserpro, no final este pacote deveria só implementar a integração da barra com o Plone.

@caduvieira seria bom ter opções para desabilitar qualquer elemento intrusivo que se decida adicionar na barra.

**Comment by idgserpro** [comment]
@hvelarde sobre elementos intrusivos sendo desabilitados em barras multilíngues, acho que podemos também discutir em https://github.com/plonegovbr/brasil.gov.barra/issues/26

**Comment by hvelarde** [comment]
acho que não: são problemas diferentes e o melhor seria abrir uma issue separada.

**Comment by caduvieira** [comment]
Sobre desabilitar elementos intrusivos na barra isso deve ser discutido com a SECOM (Agora não sei com quem exatamente) mas o @isaiascoelho pode ter uma resposta.

Já tinha sugerido sobre isso para o pessoal da SECOM mas a escolha foi NÃO ter essa opção pois, no caso do mosquito da dengue, era para 'incomodar' mesmo assim como o mosquito 'incomoda' na vida real.

E as barras em outras línguas podem ser preparadas para não ter elementos que eventualmente não cabem no contexto.

**Comment by caduvieira** [comment]
E sobre o _fallback_ da imagem do rodapé eu continuo com a sugestão de não ter imagem de _fallback_ conforme https://github.com/plonegovbr/brasil.gov.barra/issues/24#issuecomment-125995400

**Comment by idgserpro** [comment]
Sim @caduvieira, ao atender esse issue, o https://github.com/plonegovbr/brasil.gov.barra/issues/24#issuecomment-125995400 poderá ser fechado e a imagem de *fallback* removida.

**Comment by idgserpro** [comment]
Atendido em https://github.com/plonegovbr/brasil.gov.barra/pull/37.
