### ISSUE TITLE
A barra é compatível com o Plone 5?

### ISSUE THREAD

**Issue by edemir206** [plonegovbr/brasil.gov.barra#38]
Olá,

Fui instalar a barra no plone 5 porém a instancia do plone não inicia após incluir a barra nos eggs. Ela não é compatível com o plone 5 ?

**Comment by idgserpro** [comment]
O brasil.gov.barra faz parte do IDG e ainda não há suporte ao Plone 5.

O erro que você recebe é `from plone.app.controlpanel.form import ControlPanelForm`, porque o Plone 5 [deixa de usar zope.formlib para usar z3c.form](https://community.plone.org/t/plone-app-controlpanel-form-imports-on-plone-5/1208).

Se quiser tentar adaptar a barra para que ela seja compatível com Plone 4 e o Plone 5, será necessário estudar o link acima e outros pacotes que já usam dessa forma (como o collective.cover). Para mais detalhes sobre o que seria preciso para adaptar o IDG ao Plone 5, favor ver https://github.com/plonegovbr/brasil.gov.portal/issues/361.

**Comment by hvelarde** [comment]
respondendo sua pergunta, não é compatível.
