### ISSUE TITLE
Falsos positivos no teste de versão da barra

### ISSUE THREAD

**Issue by hvelarde** [plonegovbr/brasil.gov.barra#44]
O teste `test_js_external_mesma_versao_static` falha de forma aleatória e está nos atrapalhando na integração contínua do projeto:

```pytb
Failure in test test_js_external_mesma_versao_static (brasil.gov.barra.tests.test_helper.HelperViewTest)
Traceback (most recent call last):
  File "/opt/python/2.7.13/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/travis/build/plonegovbr/portal.buildout/eggs/brasil.gov.barra-1.2.1-py2.7.egg/brasil/gov/barra/tests/test_helper.py", line 110, in test_js_external_mesma_versao_static
    self.assertTrue(iguais)
  File "/opt/python/2.7.13/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
```

**Comment by hvelarde** [comment]
@caduvieira sugestões?

**Comment by caduvieira** [comment]
É a questão da língua?

https://github.com/plonegovbr/brasil.gov.barra/issues/42#issuecomment-342663873

**Comment by hvelarde** [comment]
não; eu reiniciei todos os builds e esqueci de copiar o logo do erro; se acontecer de novo vou colar aqui.

**Comment by hvelarde** [comment]
@caduvieira tem um exemplo do erro aqui:

https://travis-ci.org/plonegovbr/portal.buildout/jobs/301932775#L1978

**Comment by caduvieira** [comment]
Obrigado. Vou ver assim que puder

**Comment by hvelarde** [comment]
se tu puder me ajudar com isso aqui antes do Python 3 vou te agradecer; está me atrapalhando bastante.

**Comment by caduvieira** [comment]
Creio que seja o mesmo problema do #42 e deve ser resolvido com o PR #46

**Comment by idgserpro** [comment]
@hvelarde o @caduvieira está certo.

**Comment by hvelarde** [comment]
mesclei e fiz um release novo, vamos ver :)
