### ISSUE TITLE
Adaptar para nova barra 3.x.x (Ainda sem previsão)

### ISSUE THREAD

**Issue by idgserpro** [plonegovbr/brasil.gov.barra#49]
http://barra.governoeletronico.gov.br/teste/barra.js

Ver discussão em https://www.mail-archive.com/plonegov-br@listas.interlegis.gov.br/msg03011.html:

> Prezados,
> A SECOM solicitou uma nova versão da Barra (3.X.X) para a nova IDG que já se 
encontra no ar. Essa nova versão é major e pode quebrar coisas com a 
implementação atual nos portais. Não sei informar quando a SECOM deseja fazer a 
troca para a nova versão e sugiro os senhores atualizarem os portais.
> Por favor, se possível, testem a barra.governoeletronico.gov.br/teste com seus 
portais e forneçam feedback para a SECOM além dessa lista do IDG.
> Por favor repassem esse email para outras listas que acharem pertinente.
> Atenciosamente,
> Carlos Vieira

@caduvieira como a barra atual é a http://barra.brasil.gov.br/barra.js e essa nova se apresenta em http://barra.governoeletronico.gov.br/teste/barra.js, isso quer dizer que o endereço final acabará sendo http://barra.governoeletronico.gov.br/barra.js? Teremos as duas barras em paralelo?

**Comment by caduvieira** [comment]
A barra 3.x.x será a única disponível. E o endereço será o mesmo de http://barra.brasil.gov.br/barra.js

Quando será a troca depende da SECOM e continuo sem saber de datas.

**Comment by idgserpro** [comment]
> A barra 3.x.x será a única disponível.

Ela não é compatível com a branch 1.5.x do IDG. Isso irá alterar o layout de todos os portais que ainda estiverem na branch 1.5.x. A SECOM tem conhecimento disso? Montando um IDG 1.5.2, e usando um brasil.gov.barra substituindo a barra local pela http://barra.governoeletronico.gov.br/teste/barra.js (ou alterando o recurso da barra para http://barra.governoeletronico.gov.br/teste/barra.js em `portal_view_customizations`):

Verde
---------

![selecao_137](https://user-images.githubusercontent.com/8203476/42522788-72ef7a2c-8442-11e8-8bb5-44b03ddeaeb5.png)

![selecao_138](https://user-images.githubusercontent.com/8203476/42522796-7540ef90-8442-11e8-8054-a7a47adf18a0.png)

Amarelo
---------

![selecao_139](https://user-images.githubusercontent.com/8203476/42522803-77a2cca4-8442-11e8-9bbd-92df37c32258.png)

![selecao_140](https://user-images.githubusercontent.com/8203476/42522812-7a2c7fc4-8442-11e8-9932-38d70d21da58.png)

Azul
---------

![selecao_141](https://user-images.githubusercontent.com/8203476/42522823-7fde6e5a-8442-11e8-939f-b13e1d42269c.png)

![selecao_142](https://user-images.githubusercontent.com/8203476/42522834-835db7f2-8442-11e8-87bf-85e937fff500.png)

Branco
---------

![selecao_143](https://user-images.githubusercontent.com/8203476/42522840-867cd512-8442-11e8-8b70-208ccdc4dbeb.png)

![selecao_144](https://user-images.githubusercontent.com/8203476/42522845-89cd4ff8-8442-11e8-86ec-67779bb080fc.png)

Sem diazo aplicado (tela de escolha de tema):
-------------------------------------------------------------

![selecao_145](https://user-images.githubusercontent.com/8203476/42522772-646ae18a-8442-11e8-81ff-df7d20f6e7ab.png)

A única "compatibilidade" (ou seja, não aparece quebrado mas é questionável o jogo de cores) é quando se usa numa página de destaque, mas apenas no tema cinza (em outros temas fica com o mesmo problema anterior)

Página de destaque - Tema Cinza
----------------------------------------------

![selecao_146](https://user-images.githubusercontent.com/8203476/42522734-4aa001ae-8442-11e8-94bd-afdb50be517c.png)

Página de destaque - Tema Verde
----------------------------------------------

![selecao_147](https://user-images.githubusercontent.com/8203476/42522747-5486fbe6-8442-11e8-88d2-6d08677c5589.png)

Outra coisa: não é exatamente sobre esse issue mas, se possível, seria interessante se no arquivo compilado em barra.js tivesse a versão da barra numa variável ou em um comentário. Isso é muito útil pra efetuar debug de problemas.

**Comment by caduvieira** [comment]
> A SECOM tem conhecimento disso?
Sim. Foi feito um relatório pelo Cesar Bomfim e entregue para a SECOM sobre isso.

> seria interessante se no arquivo compilado em barra.js tivesse a versão da barra
Irei adicionar a versão na barra. Mas atualmente não posso fazer isso devido ao software público está fora do ar por causa da regra de marca de governo.

**Comment by idgserpro** [comment]
> Irei adicionar a versão na barra. 

Se possível, seria interessante tanto na branch 2.x quanto 3.x.

> Fora esse teste que vocês realizaram seria interessante ver o comportamento com o link 'Órgãos do Governo' sendo clicado/ativado pois 'empurra' para baixo toda a página com um menu de link de órgãos.

Feito apenas nos exemplos onde a barra foi renderizada corretamente:

Sem diazo aplicado (tela de escolha de tema):
--------------------------------------------------------------

![selecao_135](https://user-images.githubusercontent.com/8203476/42570896-c38ca802-84eb-11e8-9852-fdd8eea3225e.png)

Página de destaque - Tema Cinza
----------------------------------------------

![selecao_134](https://user-images.githubusercontent.com/8203476/42570903-c8621100-84eb-11e8-85ac-7bfb064e95f2.png)

O "abre e fecha" está ok.

**Comment by caduvieira** [comment]
A barra com a versão no JS vai estar disponível a partir da versão 2.2.13.

**Comment by caduvieira** [comment]
A SECOM decidiu ontem que irá ter as duas versões em paralelo. A versão atual continuará com barra.js e a nova terá o link barra_2.0.js
http://barra.governoeletronico.gov.br/teste/barra.js
http://barra.governoeletronico.gov.br/teste/barra_2.0.js

Podem verificar em http://barra.governoeletronico.gov.br/teste/ e  http://barra.governoeletronico.gov.br/teste/exemplo_antiga.html

**Comment by hvelarde** [comment]
@caduvieira o que estão precisando para atualizar o complemento da barra? como vamos ter duas versões em paralelo acho que seria importante criar um branch 1.x para manter a barra atual e deixar o master para a nova versão.

**Comment by caduvieira** [comment]
Concordo. A nova URL deveria ficar na master e ser usada pela nova IDG e ter uma branch na 1.x

**Comment by hvelarde** [comment]
fiz um novo release para a branch 1.x com o código atualizado: https://pypi.org/project/brasil.gov.barra/1.2.4/
